n = input('Digite Algo:')
print('Qual o tipo primitivo',type(n))
print('Isso é um Numero com letras?',n.isalnum())
print('Isso so tem letras maiusculas?',n.isupper())
print('Isso só tem letras minusculas?',n.islower())
print('Isso é um numerico?',n.isnumeric())
print('Isso é alfabetico?',n.isalpha())
print('Isso só contém espaços?',n.isspace())
print('Isso está capitalizado?',n.istitle())